#ifndef _COMM_INTERFACE_H_
#define _COMM_INTERFACE_H_

#include <stdint.h>

#define NUM_LOG_LEVELS 5
#define NUM_MSG_TYPE 12

#define NUM_THREAD 4
pthread_t thread[NUM_THREAD];


typedef enum MSG_TYPE_T {
	HEART_BEAT = 0,
	SENSOR_START_UP_TEST_PASSED,
	SENSOR_START_UP_TEST_FAILED,
	TASK_START_UP_TEST_PASSED,
	TASK_START_UP_TEST_FAILED,
	GESTURE_SENSOR_INACTIVE,
	DISTANCE_SENSOR_INACTIVE,
	RFID_SENSOR_INACTIVE,
	REMOTE_NODE_OFF,
	PUSH_BUTTON_SENSOR_DATA,
	DISTANCE_SENSOR_DATA,
	GESTURE_SENSOR_DATA,
	RFID_SENSOR_DATA,
	
	/*BBG SIDE DATA*/
	BBG_QUEUE_START_UP_TEST_PASSED,
	BBG_QUEUE_START_UP_TEST_FAILED,
	BBG_TC_START_UP_TEST_PASSED,
	BBG_TC_START_UP_TEST_FAILED,
	BBG_MOTOR_STOP_SIGNAL,
	BBG_FORWARD_MOTION_SIGNAL,
	BBG_RIGHT_MOTION_SIGNAL,
	BBG_LEFT_MOTION_SIGNAL,
	BBG_BACKWARD_MOTION_SIGNAL,
	
}MSG_TYPE;

typedef enum PB_DATA_T
{
    NO_PB_UPDATE = -1,
    FORWARD_BUTTON_PRESSED,
    FORWARD_BUTTON_RELEASED,
    BACKWARD_BUTTON_PRESSED,
    BACKWARD_BUTTON_RELEASED,
    LEFT_BUTTON_PRESSED,
    LEFT_BUTTON_RELEASED,
    RIGHT_BUTTON_PRESSED,
    RIGHT_BUTTON_RELEASED,
}PB_DATA;
	
typedef enum GS_DATA_T
{
	GS_ERROR = 0,
	GS_FORWARD,
	GS_BACKWARD,
	GS_RIGHT,
	GS_LEFT,
	GS_NO_GESTURE,
}GS_DATA;

typedef enum LOG_LEVELS_T
{
	ERROR = 0,
	WARNING,
	DEBUG,
	INFO,
	ALERT,
}LOG_LEVELS;
	
typedef struct TIVA_MSG_T
{
	uint8_t msg_type;
	uint8_t log_level;
	uint32_t sensor_data;
}TIVA_MSG;

const static char *const LOG_LEVEL_STRING[NUM_LOG_LEVELS] =
{
	"Error",
	"WARNING",
	"DEBUG",
	"INFO",
	"ALERT",
};

const static char *const MSG_TYPE_STRING[23] =
{
	"HEART-BEAT RECEIVED FROM TIVA",
	"SENSOR BIST PASSED",
	"SENSOR BIST FAILED",
	"TASK CREATION BIST PASSED",
	"TASK CREATION BIST FAILED",
	"GESTURE SENSOR INACTIVE",
	"DISTANCE SENSOR INACTIVE",
	"RFID SENSOR INACTIVE",
	"CONNECTION WITH REMOTE NODE LOST",
	"PUSH BUTTON SENSOR DATA",
	"DISTANCE SENSOR DATA",
	"GESTURE SENSOR DATA",
	"RFID SENSOR DATA",
	"BBG QUEUE START-UP TEST PASSED",
        "BBG QUEUE START-UP TEST FAILED",
        "BBG TC START-UP TEST PASSED",
        "BBG TC START-UP TEST FAILED",
        "BBG MOTOR STOP SIGNAL",
        "BBG FORWARD MOTION SIGNAL",
        "BBG RIGHT MOTION SIGNAL",
        "BBG LEFT MOTION SIGNAL",
        "BBG BACKWARD MOTION SIGNAL",
};

#endif
